### ISSUE TITLE
Trouble running run_NBS_cl.m demo

### ISSUE THREAD

**Issue by andreifoldes** [SNeuroble/NBS_benchmarking#1]
Greetings,
Thanks for sharing this.

I'm having some issues running run_NBS_cl.m with the demo data. I modified that following line `cluster_stat_type='Constrained'` and get:

```
Unrecognized field name "use_preaveraged_constrained".

Error in NBSrun_smn (line 346)
    if nbs.STATS.use_preaveraged_constrained

Error in run_NBS_cl (line 38)
nbs=NBSrun_smn(UI);
```

**Comment by SNeuroble** [comment]
Thanks for pointing this out, there's a bug after a recent update that should have been caught during testing. Fixed! Please pull the updated repo
